export const TOGGLE_CART_HIDDEN = "TOGGLE_CART_HIDDEN";
export const ADD_ITEM = "ADD_ITEM";
export const CLEAR_ITEM_FROM_CART = "CLEAR_ITEM_FROM_CART";
export const CONFIRM_ORDER = "CONFIRM_ORDER";
export const ORDER_BILLED = "ORDER_BILLED";
