export const TABLE_SELECTED = "TABLE_SELECTED";
export const ORDER_CONFIRMED = "ORDER_CONFIRMED";
export const AUTH_ADMIN_LOGIN = "AUTH_ADMIN_LOGIN";
export const AUTH_ADMIN_LOGOUT = "AUTH_ADMIN_LOGOUT";
export const TABLE_VACATED = "TABLE_VACATED";
